server:
  #使用https默认端口
  port: 443
  #https加密配置
  ssl:
    #证书路径
    key-store: classpath:rat403.cn.pfx
    #证书密码
    key-store-password: N2sjS3S3
    #证书类型
    key-store-type: PKCS12
    #开启ssl
    enabled: true

#mysql
spring:
  datasource:
    username: root
    password: West2online
    url: jdbc:mysql://47.115.128.193:3306/VehicleContacting?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #上传文件
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #springmail
  mail:
    host: smtp.qq.com
    username: 1006021669@qq.com
    password: pdlcmbypgwrqbfac
    default-encoding: UTF-8
    port: 465
    properties.mail.smtp.ssl.enable: true
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 30000
    client-type: jedis
  profiles:
    #
    active: dev

#日志
logging:
  file:
    path: /spring/log
    name: west2xianyu.log
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error

#mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0